import { isStr, isNum, isDigitStr, isCompNum, isBool, isTrue, isFalse, isObj, isArr, isFn, isAsyncFn, isNull, isUndef, isBoolNum, isDateStr, isArrStr, isArrNum, isArrBool, isArrObj, isArrArr, isArrFn, isArrNull, isArrUndef, isDate, isElement, isHtmlEl, isFormEl, isInputEl, isContentEditable, isNode, isError, isRegExp, isMap, isSet, isWeakMap, isWeakSet, isPromise, isSvelteSet, isSvelteMap } from "../../is/individual/index.js";

export const ALL_IS = {
    str: isStr,
    num: isNum,
    digitStr: isDigitStr,
    compNum: isCompNum,
    bool: isBool,
    "true": isTrue,
    "false": isFalse,
    obj: isObj,
    arr: isArr,
    fn: isFn,
    asyncFn: isAsyncFn,
    "null": isNull,
    undef: isUndef,
    boolNum: isBoolNum,
    dateStr: isDateStr,
    arrStr: isArrStr,
    arrNum: isArrNum,
    arrBool: isArrBool,
    arrObj: isArrObj,
    arrArr: isArrArr,
    arrFn: isArrFn,
    arrNull: isArrNull,
    arrUndef: isArrUndef,
    date: isDate,
    el: isElement,
    htmlEl: isHtmlEl,
    formEl: isFormEl,
    inputEl: isInputEl,
    contentEditable: isContentEditable,
    node: isNode,
    err: isError,
    regExp: isRegExp,
    map: isMap,
    set: isSet,
    weakMap: isWeakMap,
    weakSet: isWeakSet,
    promise: isPromise,
    svelteSet: isSvelteSet,
    svelteMap: isSvelteMap,
} as const;